# Generated by Django 4.0.4 on 2022-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaID',
            field=models.BigIntegerField(default=-8460014808239688389, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeID',
            field=models.BigIntegerField(default=977354122357669365, primary_key=True, serialize=False),
        ),
    ]
