# Generated by Django 4.0.4 on 2022-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_area_areaid_alter_route_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaID',
            field=models.BigIntegerField(default=-8410464605351238393, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeID',
            field=models.BigIntegerField(default=1472480229668607362, primary_key=True, serialize=False),
        ),
    ]
