# Generated by Django 4.0.4 on 2022-06-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_area_areaid_alter_route_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaID',
            field=models.BigIntegerField(default=7613386024099898507, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeID',
            field=models.BigIntegerField(default=2431167339454534041, primary_key=True, serialize=False),
        ),
    ]
